<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DoctorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('doctors')->insert([
            [
                'apellidos' => 'Mamani Quispe',
                'nombres' => 'Juan Carlos',
                'ci' => '4012345',
                'especialidad' => 'Medicina General',
                'telefono' => '71234567',
                'email' => 'juan.mamani@hospital.com',
                'foto' => null,
            ],
            [
                'apellidos' => 'Perez Flores',
                'nombres' => 'Maria Elena',
                'ci' => '4023456',
                'especialidad' => 'Pediatria',
                'telefono' => '72345678',
                'email' => 'maria.perez@hospital.com',
                'foto' => null,
            ],
            [
                'apellidos' => 'Quispe Condori',
                'nombres' => 'Luis Fernando',
                'ci' => '4034567',
                'especialidad' => 'Cardiologia',
                'telefono' => '73456789',
                'email' => 'luis.quispe@hospital.com',
                'foto' => null,
            ],
            [
                'apellidos' => 'Lopez Vargas',
                'nombres' => 'Ana Sofia',
                'ci' => '4045678',
                'especialidad' => 'Dermatologia',
                'telefono' => '74567890',
                'email' => 'ana.lopez@hospital.com',
                'foto' => null,
            ],
            [
                'apellidos' => 'Garcia Rojas',
                'nombres' => 'Carlos Alberto',
                'ci' => '4056789',
                'especialidad' => 'Traumatologia',
                'telefono' => '75678901',
                'email' => 'carlos.garcia@hospital.com',
                'foto' => null,
            ],
            [
                'apellidos' => 'Rodriguez Cruz',
                'nombres' => 'Patricia Andrea',
                'ci' => '4067890',
                'especialidad' => 'Ginecologia',
                'telefono' => '76789012',
                'email' => 'patricia.rodriguez@hospital.com',
                'foto' => null,
            ],
            [
                'apellidos' => 'Fernandez Choque',
                'nombres' => 'Miguel Angel',
                'ci' => '4078901',
                'especialidad' => 'Neurologia',
                'telefono' => '77890123',
                'email' => 'miguel.fernandez@hospital.com',
                'foto' => null,
            ],
            [
                'apellidos' => 'Torrez Soria',
                'nombres' => 'Gabriela Paola',
                'ci' => '4089012',
                'especialidad' => 'Oftalmologia',
                'telefono' => '78901234',
                'email' => 'gabriela.torrez@hospital.com',
                'foto' => null,
            ],
            [
                'apellidos' => 'Gutierrez Molina',
                'nombres' => 'Roberto Daniel',
                'ci' => '4090123',
                'especialidad' => 'Urologia',
                'telefono' => '79012345',
                'email' => 'roberto.gutierrez@hospital.com',
                'foto' => null,
            ],
            [
                'apellidos' => 'Sanchez Paredes',
                'nombres' => 'Laura Beatriz',
                'ci' => '4101234',
                'especialidad' => 'Endocrinologia',
                'telefono' => '70123456',
                'email' => 'laura.sanchez@hospital.com',
                'foto' => null,
            ],
            [
                'apellidos' => 'Rojas Mendoza',
                'nombres' => 'Diego Alejandro',
                'ci' => '4112345',
                'especialidad' => 'Psiquiatria',
                'telefono' => '71234568',
                'email' => 'diego.rojas@hospital.com',
                'foto' => null,
            ],
            [
                'apellidos' => 'Vargas Salazar',
                'nombres' => 'Daniela Nicole',
                'ci' => '4123456',
                'especialidad' => 'Nutricion',
                'telefono' => '72345679',
                'email' => 'daniela.vargas@hospital.com',
                'foto' => null,
            ],
            [
                'apellidos' => 'Condori Mamani',
                'nombres' => 'Pedro Antonio',
                'ci' => '4134567',
                'especialidad' => 'Cirugia General',
                'telefono' => '73456780',
                'email' => 'pedro.condori@hospital.com',
                'foto' => null,
            ],
            [
                'apellidos' => 'Flores Nina',
                'nombres' => 'Carmen Lucia',
                'ci' => '4145678',
                'especialidad' => 'Odontologia',
                'telefono' => '74567891',
                'email' => 'carmen.flores@hospital.com',
                'foto' => null,
            ],
            [
                'apellidos' => 'Mendoza Arias',
                'nombres' => 'Jorge Luis',
                'ci' => '4156789',
                'especialidad' => 'Neumologia',
                'telefono' => '75678902',
                'email' => 'jorge.mendoza@hospital.com',
                'foto' => null,
            ],
            [
                'apellidos' => 'Soria Alanes',
                'nombres' => 'Monica Isabel',
                'ci' => '4167890',
                'especialidad' => 'Reumatologia',
                'telefono' => '76789013',
                'email' => 'monica.soria@hospital.com',
                'foto' => null,
            ],
            [
                'apellidos' => 'Cruz Romero',
                'nombres' => 'Fernando Javier',
                'ci' => '4178901',
                'especialidad' => 'Oncologia',
                'telefono' => '77890124',
                'email' => 'fernando.cruz@hospital.com',
                'foto' => null,
            ],
            [
                'apellidos' => 'Choque Huanca',
                'nombres' => 'Rosa Maria',
                'ci' => '4189012',
                'especialidad' => 'Hematologia',
                'telefono' => '78901235',
                'email' => 'rosa.choque@hospital.com',
                'foto' => null,
            ],
            [
                'apellidos' => 'Molina Castro',
                'nombres' => 'Oscar Eduardo',
                'ci' => '4190123',
                'especialidad' => 'Gastroenterologia',
                'telefono' => '79012346',
                'email' => 'oscar.molina@hospital.com',
                'foto' => null,
            ],
            [
                'apellidos' => 'Paredes Silva',
                'nombres' => 'Valeria Fernanda',
                'ci' => '4201234',
                'especialidad' => 'Infectologia',
                'telefono' => '70123457',
                'email' => 'valeria.paredes@hospital.com',
                'foto' => null,
            ],
            [
                'apellidos' => 'Salazar Vargas',
                'nombres' => 'Andres Mauricio',
                'ci' => '4212345',
                'especialidad' => 'Otorrinolaringologia',
                'telefono' => '71234569',
                'email' => 'andres.salazar@hospital.com',
                'foto' => null,
            ],
            [
                'apellidos' => 'Nina Quispe',
                'nombres' => 'Silvia Alejandra',
                'ci' => '4223456',
                'especialidad' => 'Medicina Interna',
                'telefono' => '72345680',
                'email' => 'silvia.nina@hospital.com',
                'foto' => null,
            ],
            [
                'apellidos' => 'Arias Gutierrez',
                'nombres' => 'Martin Enrique',
                'ci' => '4234567',
                'especialidad' => 'Anestesiologia',
                'telefono' => '73456781',
                'email' => 'martin.arias@hospital.com',
                'foto' => null,
            ],
            [
                'apellidos' => 'Romero Diaz',
                'nombres' => 'Claudia Veronica',
                'ci' => '4245678',
                'especialidad' => 'Cirugia Plastica',
                'telefono' => '74567892',
                'email' => 'claudia.romero@hospital.com',
                'foto' => null,
            ],
            [
                'apellidos' => 'Huanca Flores',
                'nombres' => 'Victor Hugo',
                'ci' => '4256789',
                'especialidad' => 'Cardiologia',
                'telefono' => '75678903',
                'email' => 'victor.huanca@hospital.com',
                'foto' => null,
            ],
            [
                'apellidos' => 'Castro Rojas',
                'nombres' => 'Natalia Andrea',
                'ci' => '4267890',
                'especialidad' => 'Pediatria',
                'telefono' => '76789014',
                'email' => 'natalia.castro@hospital.com',
                'foto' => null,
            ],
            [
                'apellidos' => 'Silva Fernandez',
                'nombres' => 'Eduardo Jose',
                'ci' => '4278901',
                'especialidad' => 'Medicina General',
                'telefono' => '77890125',
                'email' => 'eduardo.silva@hospital.com',
                'foto' => null,
            ],
            [
                'apellidos' => 'Diaz Mendoza',
                'nombres' => 'Paola Cristina',
                'ci' => '4289012',
                'especialidad' => 'Ginecologia',
                'telefono' => '78901236',
                'email' => 'paola.diaz@hospital.com',
                'foto' => null,
            ],
            [
                'apellidos' => 'Romero Choque',
                'nombres' => 'Alejandro Rene',
                'ci' => '4290123',
                'especialidad' => 'Traumatologia',
                'telefono' => '79012347',
                'email' => 'alejandro.romero@hospital.com',
                'foto' => null,
            ],
            [
                'apellidos' => 'Alanes Condori',
                'nombres' => 'Marcela Patricia',
                'ci' => '4301234',
                'especialidad' => 'Dermatologia',
                'telefono' => '70123458',
                'email' => 'marcela.alanes@hospital.com',
                'foto' => null,
            ],
        ]);
    }
}

