<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InsumoSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('insumos')->insert([
            [
                'codigo' => 'MED-001',
                'nombre' => 'Paracetamol 500 mg',
                'tipo' => 'MEDICAMENTO',
                'descripcion' => 'Analgésico y antipirético de 500 mg.',
                'unidad_medida' => 'TABLETA',
                'stock' => 250,
                'stock_minimo' => 50,
                'precio_compra' => 0.50,
                'precio_venta' => 1.00,
                'estado' => true,
            ],
            [
                'codigo' => 'MED-002',
                'nombre' => 'Ibuprofeno 400 mg',
                'tipo' => 'MEDICAMENTO',
                'descripcion' => 'Antiinflamatorio y analgésico de 400 mg.',
                'unidad_medida' => 'TABLETA',
                'stock' => 180,
                'stock_minimo' => 40,
                'precio_compra' => 0.80,
                'precio_venta' => 1.50,
                'estado' => true,
            ],
            [
                'codigo' => 'MED-003',
                'nombre' => 'Amoxicilina 500 mg',
                'tipo' => 'MEDICAMENTO',
                'descripcion' => 'Antibiótico de amplio espectro.',
                'unidad_medida' => 'CAPSULA',
                'stock' => 120,
                'stock_minimo' => 30,
                'precio_compra' => 1.20,
                'precio_venta' => 2.00,
                'estado' => true,
            ],
            [
                'codigo' => 'MED-004',
                'nombre' => 'Omeprazol 20 mg',
                'tipo' => 'MEDICAMENTO',
                'descripcion' => 'Medicamento utilizado para reducir la acidez gástrica.',
                'unidad_medida' => 'CAPSULA',
                'stock' => 200,
                'stock_minimo' => 40,
                'precio_compra' => 0.70,
                'precio_venta' => 1.30,
                'estado' => true,
            ],
            [
                'codigo' => 'MED-005',
                'nombre' => 'Losartan 50 mg',
                'tipo' => 'MEDICAMENTO',
                'descripcion' => 'Medicamento antihipertensivo.',
                'unidad_medida' => 'TABLETA',
                'stock' => 150,
                'stock_minimo' => 30,
                'precio_compra' => 1.00,
                'precio_venta' => 1.80,
                'estado' => true,
            ],
            [
                'codigo' => 'MED-006',
                'nombre' => 'Metformina 850 mg',
                'tipo' => 'MEDICAMENTO',
                'descripcion' => 'Medicamento utilizado para el control de la glucosa.',
                'unidad_medida' => 'TABLETA',
                'stock' => 160,
                'stock_minimo' => 35,
                'precio_compra' => 0.90,
                'precio_venta' => 1.60,
                'estado' => true,
            ],
            [
                'codigo' => 'MED-007',
                'nombre' => 'Diclofenaco 50 mg',
                'tipo' => 'MEDICAMENTO',
                'descripcion' => 'Antiinflamatorio no esteroideo.',
                'unidad_medida' => 'TABLETA',
                'stock' => 100,
                'stock_minimo' => 25,
                'precio_compra' => 0.60,
                'precio_venta' => 1.20,
                'estado' => true,
            ],
            [
                'codigo' => 'MED-008',
                'nombre' => 'Azitromicina 500 mg',
                'tipo' => 'MEDICAMENTO',
                'descripcion' => 'Antibiótico macrólido.',
                'unidad_medida' => 'TABLETA',
                'stock' => 80,
                'stock_minimo' => 20,
                'precio_compra' => 2.50,
                'precio_venta' => 4.00,
                'estado' => true,
            ],
            [
                'codigo' => 'MED-009',
                'nombre' => 'Salbutamol 100 mcg',
                'tipo' => 'MEDICAMENTO',
                'descripcion' => 'Medicamento broncodilatador en aerosol.',
                'unidad_medida' => 'FRASCO',
                'stock' => 45,
                'stock_minimo' => 10,
                'precio_compra' => 18.00,
                'precio_venta' => 25.00,
                'estado' => true,
            ],
            [
                'codigo' => 'MED-010',
                'nombre' => 'Loratadina 10 mg',
                'tipo' => 'MEDICAMENTO',
                'descripcion' => 'Antihistamínico para síntomas de alergia.',
                'unidad_medida' => 'TABLETA',
                'stock' => 130,
                'stock_minimo' => 30,
                'precio_compra' => 0.70,
                'precio_venta' => 1.40,
                'estado' => true,
            ],
            [
                'codigo' => 'MED-011',
                'nombre' => 'Clorfenamina 4 mg',
                'tipo' => 'MEDICAMENTO',
                'descripcion' => 'Antihistamínico.',
                'unidad_medida' => 'TABLETA',
                'stock' => 90,
                'stock_minimo' => 20,
                'precio_compra' => 0.40,
                'precio_venta' => 0.90,
                'estado' => true,
            ],
            [
                'codigo' => 'MED-012',
                'nombre' => 'Dexametasona 4 mg',
                'tipo' => 'MEDICAMENTO',
                'descripcion' => 'Corticoide de uso médico.',
                'unidad_medida' => 'TABLETA',
                'stock' => 70,
                'stock_minimo' => 15,
                'precio_compra' => 1.20,
                'precio_venta' => 2.20,
                'estado' => true,
            ],
            [
                'codigo' => 'MED-013',
                'nombre' => 'Ceftriaxona 1 g',
                'tipo' => 'MEDICAMENTO',
                'descripcion' => 'Antibiótico de uso hospitalario.',
                'unidad_medida' => 'FRASCO',
                'stock' => 60,
                'stock_minimo' => 15,
                'precio_compra' => 8.00,
                'precio_venta' => 12.00,
                'estado' => true,
            ],
            [
                'codigo' => 'MED-014',
                'nombre' => 'Solución salina 0.9%',
                'tipo' => 'MEDICAMENTO',
                'descripcion' => 'Solución fisiológica para uso médico.',
                'unidad_medida' => 'BOLSA',
                'stock' => 100,
                'stock_minimo' => 20,
                'precio_compra' => 6.00,
                'precio_venta' => 9.00,
                'estado' => true,
            ],
            [
                'codigo' => 'MED-015',
                'nombre' => 'Alcohol medicinal 70%',
                'tipo' => 'MEDICAMENTO',
                'descripcion' => 'Antiséptico para limpieza de la piel.',
                'unidad_medida' => 'FRASCO',
                'stock' => 75,
                'stock_minimo' => 15,
                'precio_compra' => 8.00,
                'precio_venta' => 12.00,
                'estado' => true,
            ],

            // INSUMOS MÉDICOS

            [
                'codigo' => 'INS-001',
                'nombre' => 'Jeringa 5 ml',
                'tipo' => 'INSUMO_MEDICO',
                'descripcion' => 'Jeringa descartable de 5 ml.',
                'unidad_medida' => 'UNIDAD',
                'stock' => 500,
                'stock_minimo' => 100,
                'precio_compra' => 0.80,
                'precio_venta' => 1.50,
                'estado' => true,
            ],
            [
                'codigo' => 'INS-002',
                'nombre' => 'Jeringa 10 ml',
                'tipo' => 'INSUMO_MEDICO',
                'descripcion' => 'Jeringa descartable de 10 ml.',
                'unidad_medida' => 'UNIDAD',
                'stock' => 400,
                'stock_minimo' => 80,
                'precio_compra' => 1.00,
                'precio_venta' => 1.80,
                'estado' => true,
            ],
            [
                'codigo' => 'INS-003',
                'nombre' => 'Guantes de látex',
                'tipo' => 'INSUMO_MEDICO',
                'descripcion' => 'Guantes desechables para procedimientos médicos.',
                'unidad_medida' => 'CAJA',
                'stock' => 80,
                'stock_minimo' => 20,
                'precio_compra' => 35.00,
                'precio_venta' => 50.00,
                'estado' => true,
            ],
            [
                'codigo' => 'INS-004',
                'nombre' => 'Mascarilla quirúrgica',
                'tipo' => 'INSUMO_MEDICO',
                'descripcion' => 'Mascarilla descartable de uso médico.',
                'unidad_medida' => 'CAJA',
                'stock' => 100,
                'stock_minimo' => 25,
                'precio_compra' => 20.00,
                'precio_venta' => 30.00,
                'estado' => true,
            ],
            [
                'codigo' => 'INS-005',
                'nombre' => 'Gasa estéril 10x10 cm',
                'tipo' => 'INSUMO_MEDICO',
                'descripcion' => 'Gasa estéril para curaciones.',
                'unidad_medida' => 'PAQUETE',
                'stock' => 150,
                'stock_minimo' => 30,
                'precio_compra' => 4.00,
                'precio_venta' => 7.00,
                'estado' => true,
            ],
            [
                'codigo' => 'INS-006',
                'nombre' => 'Algodón hidrófilo',
                'tipo' => 'INSUMO_MEDICO',
                'descripcion' => 'Algodón para limpieza y procedimientos médicos.',
                'unidad_medida' => 'PAQUETE',
                'stock' => 90,
                'stock_minimo' => 20,
                'precio_compra' => 5.00,
                'precio_venta' => 8.00,
                'estado' => true,
            ],
            [
                'codigo' => 'INS-007',
                'nombre' => 'Venda elástica 10 cm',
                'tipo' => 'INSUMO_MEDICO',
                'descripcion' => 'Venda elástica para soporte y curaciones.',
                'unidad_medida' => 'UNIDAD',
                'stock' => 70,
                'stock_minimo' => 15,
                'precio_compra' => 6.00,
                'precio_venta' => 10.00,
                'estado' => true,
            ],
            [
                'codigo' => 'INS-008',
                'nombre' => 'Cinta médica adhesiva',
                'tipo' => 'INSUMO_MEDICO',
                'descripcion' => 'Cinta adhesiva para fijación de apósitos.',
                'unidad_medida' => 'ROLLO',
                'stock' => 50,
                'stock_minimo' => 10,
                'precio_compra' => 7.00,
                'precio_venta' => 12.00,
                'estado' => true,
            ],
            [
                'codigo' => 'INS-009',
                'nombre' => 'Catéter intravenoso 20G',
                'tipo' => 'INSUMO_MEDICO',
                'descripcion' => 'Catéter para administración intravenosa.',
                'unidad_medida' => 'UNIDAD',
                'stock' => 120,
                'stock_minimo' => 25,
                'precio_compra' => 2.50,
                'precio_venta' => 4.00,
                'estado' => true,
            ],
            [
                'codigo' => 'INS-010',
                'nombre' => 'Equipo de venoclisis',
                'tipo' => 'INSUMO_MEDICO',
                'descripcion' => 'Equipo descartable para administración de soluciones.',
                'unidad_medida' => 'UNIDAD',
                'stock' => 100,
                'stock_minimo' => 20,
                'precio_compra' => 5.00,
                'precio_venta' => 8.00,
                'estado' => true,
            ],
            [
                'codigo' => 'INS-011',
                'nombre' => 'Termómetro digital',
                'tipo' => 'INSUMO_MEDICO',
                'descripcion' => 'Termómetro digital para medición de temperatura.',
                'unidad_medida' => 'UNIDAD',
                'stock' => 25,
                'stock_minimo' => 5,
                'precio_compra' => 25.00,
                'precio_venta' => 40.00,
                'estado' => true,
            ],
            [
                'codigo' => 'INS-012',
                'nombre' => 'Oxímetro de pulso',
                'tipo' => 'INSUMO_MEDICO',
                'descripcion' => 'Dispositivo para medir saturación de oxígeno.',
                'unidad_medida' => 'UNIDAD',
                'stock' => 15,
                'stock_minimo' => 3,
                'precio_compra' => 120.00,
                'precio_venta' => 180.00,
                'estado' => true,
            ],
            [
                'codigo' => 'INS-013',
                'nombre' => 'Tensiómetro digital',
                'tipo' => 'INSUMO_MEDICO',
                'descripcion' => 'Dispositivo digital para medir presión arterial.',
                'unidad_medida' => 'UNIDAD',
                'stock' => 12,
                'stock_minimo' => 3,
                'precio_compra' => 180.00,
                'precio_venta' => 250.00,
                'estado' => true,
            ],
            [
                'codigo' => 'INS-014',
                'nombre' => 'Bata quirúrgica descartable',
                'tipo' => 'INSUMO_MEDICO',
                'descripcion' => 'Bata descartable para procedimientos médicos.',
                'unidad_medida' => 'UNIDAD',
                'stock' => 60,
                'stock_minimo' => 15,
                'precio_compra' => 12.00,
                'precio_venta' => 20.00,
                'estado' => true,
            ],
            [
                'codigo' => 'INS-015',
                'nombre' => 'Gorro quirúrgico',
                'tipo' => 'INSUMO_MEDICO',
                'descripcion' => 'Gorro descartable para procedimientos médicos.',
                'unidad_medida' => 'UNIDAD',
                'stock' => 100,
                'stock_minimo' => 20,
                'precio_compra' => 2.00,
                'precio_venta' => 4.00,
                'estado' => true,
            ],
        ]);
    }
}

