<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PatientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('patients')->insert([
            [
                'apellidos' => 'Mamani Quispe',
                'nombres' => 'Juan Carlos',
                'fecha_nacimiento' => '1990-05-15',
                'ci' => '6012345',
                'telefono' => '71234567',
                'email' => 'juan.mamani@gmail.com',
                'direccion' => 'Av. Blanco Galindo #123',
                'genero' => 'Masculino',
                'fotografia' => null,
            ],
            [
                'apellidos' => 'Perez Flores',
                'nombres' => 'Maria Elena',
                'fecha_nacimiento' => '1988-08-22',
                'ci' => '6023456',
                'telefono' => '72345678',
                'email' => 'maria.perez@gmail.com',
                'direccion' => 'Calle Sucre #245',
                'genero' => 'Femenino',
                'fotografia' => null,
            ],
            [
                'apellidos' => 'Quispe Condori',
                'nombres' => 'Luis Fernando',
                'fecha_nacimiento' => '1995-01-10',
                'ci' => '6034567',
                'telefono' => '73456789',
                'email' => 'luis.quispe@gmail.com',
                'direccion' => 'Av. Petrolera #456',
                'genero' => 'Masculino',
                'fotografia' => null,
            ],
            [
                'apellidos' => 'Lopez Vargas',
                'nombres' => 'Ana Sofia',
                'fecha_nacimiento' => '1992-11-03',
                'ci' => '6045678',
                'telefono' => '74567890',
                'email' => 'ana.lopez@gmail.com',
                'direccion' => 'Calle Cochabamba #321',
                'genero' => 'Femenino',
                'fotografia' => null,
            ],
            [
                'apellidos' => 'Garcia Rojas',
                'nombres' => 'Carlos Alberto',
                'fecha_nacimiento' => '1985-03-18',
                'ci' => '6056789',
                'telefono' => '75678901',
                'email' => 'carlos.garcia@gmail.com',
                'direccion' => 'Av. Circunvalacion #567',
                'genero' => 'Masculino',
                'fotografia' => null,
            ],
            [
                'apellidos' => 'Rodriguez Cruz',
                'nombres' => 'Patricia Andrea',
                'fecha_nacimiento' => '1998-07-25',
                'ci' => '6067890',
                'telefono' => '76789012',
                'email' => 'patricia.rodriguez@gmail.com',
                'direccion' => 'Calle Bolivar #789',
                'genero' => 'Femenino',
                'fotografia' => null,
            ],
            [
                'apellidos' => 'Fernandez Choque',
                'nombres' => 'Miguel Angel',
                'fecha_nacimiento' => '1991-09-12',
                'ci' => '6078901',
                'telefono' => '77890123',
                'email' => 'miguel.fernandez@gmail.com',
                'direccion' => 'Av. America #852',
                'genero' => 'Masculino',
                'fotografia' => null,
            ],
            [
                'apellidos' => 'Torrez Soria',
                'nombres' => 'Gabriela Paola',
                'fecha_nacimiento' => '1996-12-30',
                'ci' => '6089012',
                'telefono' => '78901234',
                'email' => 'gabriela.torrez@gmail.com',
                'direccion' => 'Calle Lanza #963',
                'genero' => 'Femenino',
                'fotografia' => null,
            ],
            [
                'apellidos' => 'Gutierrez Molina',
                'nombres' => 'Roberto Daniel',
                'fecha_nacimiento' => '1987-04-08',
                'ci' => '6090123',
                'telefono' => '79012345',
                'email' => 'roberto.gutierrez@gmail.com',
                'direccion' => 'Av. Melchor Perez #147',
                'genero' => 'Masculino',
                'fotografia' => null,
            ],
            [
                'apellidos' => 'Sanchez Paredes',
                'nombres' => 'Laura Beatriz',
                'fecha_nacimiento' => '1993-06-19',
                'ci' => '6101234',
                'telefono' => '70123456',
                'email' => 'laura.sanchez@gmail.com',
                'direccion' => 'Calle Tarija #258',
                'genero' => 'Femenino',
                'fotografia' => null,
            ],
            [
                'apellidos' => 'Rojas Mendoza',
                'nombres' => 'Diego Alejandro',
                'fecha_nacimiento' => '1999-02-14',
                'ci' => '6112345',
                'telefono' => '71234568',
                'email' => 'diego.rojas@gmail.com',
                'direccion' => 'Av. Simon Lopez #369',
                'genero' => 'Masculino',
                'fotografia' => null,
            ],
            [
                'apellidos' => 'Vargas Salazar',
                'nombres' => 'Daniela Nicole',
                'fecha_nacimiento' => '2000-10-05',
                'ci' => '6123456',
                'telefono' => '72345679',
                'email' => 'daniela.vargas@gmail.com',
                'direccion' => 'Calle Ecuador #741',
                'genero' => 'Femenino',
                'fotografia' => null,
            ],
            [
                'apellidos' => 'Condori Mamani',
                'nombres' => 'Pedro Antonio',
                'fecha_nacimiento' => '1982-01-27',
                'ci' => '6134567',
                'telefono' => '73456780',
                'email' => 'pedro.condori@gmail.com',
                'direccion' => 'Av. Petrolera #852',
                'genero' => 'Masculino',
                'fotografia' => null,
            ],
            [
                'apellidos' => 'Flores Nina',
                'nombres' => 'Carmen Lucia',
                'fecha_nacimiento' => '1994-05-11',
                'ci' => '6145678',
                'telefono' => '74567891',
                'email' => 'carmen.flores@gmail.com',
                'direccion' => 'Calle Aroma #963',
                'genero' => 'Femenino',
                'fotografia' => null,
            ],
            [
                'apellidos' => 'Mendoza Arias',
                'nombres' => 'Jorge Luis',
                'fecha_nacimiento' => '1989-08-17',
                'ci' => '6156789',
                'telefono' => '75678902',
                'email' => 'jorge.mendoza@gmail.com',
                'direccion' => 'Av. Beijing #159',
                'genero' => 'Masculino',
                'fotografia' => null,
            ],
            [
                'apellidos' => 'Soria Alanes',
                'nombres' => 'Monica Isabel',
                'fecha_nacimiento' => '1997-03-22',
                'ci' => '6167890',
                'telefono' => '76789013',
                'email' => 'monica.soria@gmail.com',
                'direccion' => 'Calle Potosi #357',
                'genero' => 'Femenino',
                'fotografia' => null,
            ],
            [
                'apellidos' => 'Cruz Romero',
                'nombres' => 'Fernando Javier',
                'fecha_nacimiento' => '1984-11-09',
                'ci' => '6178901',
                'telefono' => '77890124',
                'email' => 'fernando.cruz@gmail.com',
                'direccion' => 'Av. Ayacucho #468',
                'genero' => 'Masculino',
                'fotografia' => null,
            ],
            [
                'apellidos' => 'Choque Huanca',
                'nombres' => 'Rosa Maria',
                'fecha_nacimiento' => '1990-07-16',
                'ci' => '6189012',
                'telefono' => '78901235',
                'email' => 'rosa.choque@gmail.com',
                'direccion' => 'Calle Antezana #579',
                'genero' => 'Femenino',
                'fotografia' => null,
            ],
            [
                'apellidos' => 'Molina Castro',
                'nombres' => 'Oscar Eduardo',
                'fecha_nacimiento' => '1986-02-28',
                'ci' => '6190123',
                'telefono' => '79012346',
                'email' => 'oscar.molina@gmail.com',
                'direccion' => 'Av. Santa Cruz #681',
                'genero' => 'Masculino',
                'fotografia' => null,
            ],
            [
                'apellidos' => 'Paredes Silva',
                'nombres' => 'Valeria Fernanda',
                'fecha_nacimiento' => '2001-09-13',
                'ci' => '6201234',
                'telefono' => '70123457',
                'email' => 'valeria.paredes@gmail.com',
                'direccion' => 'Calle España #792',
                'genero' => 'Femenino',
                'fotografia' => null,
            ],
            [
                'apellidos' => 'Salazar Vargas',
                'nombres' => 'Andres Mauricio',
                'fecha_nacimiento' => '1993-12-07',
                'ci' => '6212345',
                'telefono' => '71234569',
                'email' => 'andres.salazar@gmail.com',
                'direccion' => 'Av. Beijing #813',
                'genero' => 'Masculino',
                'fotografia' => null,
            ],
            [
                'apellidos' => 'Nina Quispe',
                'nombres' => 'Silvia Alejandra',
                'fecha_nacimiento' => '1995-04-21',
                'ci' => '6223456',
                'telefono' => '72345680',
                'email' => 'silvia.nina@gmail.com',
                'direccion' => 'Calle Baptista #924',
                'genero' => 'Femenino',
                'fotografia' => null,
            ],
            [
                'apellidos' => 'Arias Gutierrez',
                'nombres' => 'Martin Enrique',
                'fecha_nacimiento' => '1981-06-15',
                'ci' => '6234567',
                'telefono' => '73456781',
                'email' => 'martin.arias@gmail.com',
                'direccion' => 'Av. Petrolera #135',
                'genero' => 'Masculino',
                'fotografia' => null,
            ],
            [
                'apellidos' => 'Romero Diaz',
                'nombres' => 'Claudia Veronica',
                'fecha_nacimiento' => '1989-10-29',
                'ci' => '6245678',
                'telefono' => '74567892',
                'email' => 'claudia.romero@gmail.com',
                'direccion' => 'Calle Ladislao Cabrera #246',
                'genero' => 'Femenino',
                'fotografia' => null,
            ],
            [
                'apellidos' => 'Huanca Flores',
                'nombres' => 'Victor Hugo',
                'fecha_nacimiento' => '1979-08-04',
                'ci' => '6256789',
                'telefono' => '75678903',
                'email' => 'victor.huanca@gmail.com',
                'direccion' => 'Av. Blanco Galindo #357',
                'genero' => 'Masculino',
                'fotografia' => null,
            ],
            [
                'apellidos' => 'Castro Rojas',
                'nombres' => 'Natalia Andrea',
                'fecha_nacimiento' => '1998-01-18',
                'ci' => '6267890',
                'telefono' => '76789014',
                'email' => 'natalia.castro@gmail.com',
                'direccion' => 'Calle Sucre #468',
                'genero' => 'Femenino',
                'fotografia' => null,
            ],
            [
                'apellidos' => 'Silva Fernandez',
                'nombres' => 'Eduardo Jose',
                'fecha_nacimiento' => '1983-05-26',
                'ci' => '6278901',
                'telefono' => '77890125',
                'email' => 'eduardo.silva@gmail.com',
                'direccion' => 'Av. America #579',
                'genero' => 'Masculino',
                'fotografia' => null,
            ],
            [
                'apellidos' => 'Diaz Mendoza',
                'nombres' => 'Paola Cristina',
                'fecha_nacimiento' => '1996-11-12',
                'ci' => '6289012',
                'telefono' => '78901236',
                'email' => 'paola.diaz@gmail.com',
                'direccion' => 'Calle Bolivar #681',
                'genero' => 'Femenino',
                'fotografia' => null,
            ],
            [
                'apellidos' => 'Romero Choque',
                'nombres' => 'Alejandro Rene',
                'fecha_nacimiento' => '1991-03-05',
                'ci' => '6290123',
                'telefono' => '79012347',
                'email' => 'alejandro.romero@gmail.com',
                'direccion' => 'Av. Circunvalacion #792',
                'genero' => 'Masculino',
                'fotografia' => null,
            ],
            [
                'apellidos' => 'Alanes Condori',
                'nombres' => 'Marcela Patricia',
                'fecha_nacimiento' => '1994-09-24',
                'ci' => '6301234',
                'telefono' => '70123458',
                'email' => 'marcela.alanes@gmail.com',
                'direccion' => 'Calle Tarija #813',
                'genero' => 'Femenino',
                'fotografia' => null,
            ],
        ]);
    }
}

